#
#  TDS: 11/2011
#  PROTOTYPE - PROTOTYPE - PROTOTYPE
#  If you are surprised to see this here, just ignore it.
#
Package: common-msgs
Version: 3.4.5
Section: misc
Priority: extra
Architecture: all
Depends: catkin, genmsg, std_msgs
Description: Common ROS Messages
Author: Troy Straszheim <straszheim@willowgarage.com>, Morten Kjaergaard, Ken Conley
Maintainer: Troy Straszheim <straszheim@willowgarage.com>
Homepage: http://www.ros.org

Catkin-ProjectName: common_msgs
Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake
