Catkin-ProjectName: common_msgs
Version: 1.6.0
Description: Common ROS Messages
Author: Troy Straszheim <straszheim@willowgarage.com>, Morten Kjaergaard, Ken Conley
Maintainer: Troy Straszheim <straszheim@willowgarage.com>
Homepage: http://www.ros.org

Catkin-CopyrightType:  willowgarage
Catkin-DebRulesType: cmake.catkin

Depends: catkin, genmsg, gencpp, genpy, gentypelibxml, genpybindings, std_msgs

Release-Pull: git://github.com/wg-debs/common_msgs.git
Release-Push: git@github.com:wg-debs/common_msgs.git
