#
#  TDS: 11/2011
#  PROTOTYPE - PROTOTYPE - PROTOTYPE
#  If you are surprised to see this here, just ignore it.
#
Package: common-msgs
Version: 3.4.5
Section: misc
Priority: extra
Architecture: all
Depends: ${misc:Depends} python-empy, cmake, make, 
         @(CATKIN_PACKAGE_PREFIX)genmsg, @(CATKIN_PACKAGE_PREFIX)genpy, @(CATKIN_PACKAGE_PREFIX)gencpp
Build-Depends: debhelper (>= 7), cmake, gcc, make, python, python-empy, python-setuptools, 
               @(CATKIN_PACKAGE_PREFIX)catkin, @(CATKIN_PACKAGE_PREFIX)genmsg, 
               @(CATKIN_PACKAGE_PREFIX)genpy, @(CATKIN_PACKAGE_PREFIX)gencpp
Description: Willow Garage low level build system macros and infrastructure
Author: Troy Straszheim <straszheim@willowgarage.com>, Morten Kjaergaard, Ken Conley
Maintainer: Troy Straszheim <straszheim@willowgarage.com>
Homepage: http://www.ros.org

Catkin-ProjectName: common_msgs
Catkin-CopyrightType:  willowgarage
Catkin-Depends: catkin, genmsg, std_msgs
Catkin-DebRulesType: cmake
