#
#  TDS: 11/2011
#  PROTOTYPE - PROTOTYPE - PROTOTYPE
#  If you are surprised to see this here, just ignore it.
#
Package: common-msgs
Version: 3.4.5
Section: misc
Priority: extra
Architecture: all
Depends: ${misc:Depends} python-empy, cmake, make,
         @(PackagePrefix)genmsg, @(PackagePrefix)genpy, @(PackagePrefix)gencpp,
         @(PackagePrefix)std-msgs
Build-Depends: debhelper (>= 7), cmake, gcc, make, python, python-empy, python-setuptools,
               @(PackagePrefix)catkin, @(PackagePrefix)genmsg,
               @(PackagePrefix)genpy, @(PackagePrefix)gencpp, @(PackagePrefix)genpybindings,
               @(PackagePrefix)std-msgs
Description: Common ROS Messages
Author: Troy Straszheim <straszheim@willowgarage.com>, Morten Kjaergaard, Ken Conley
Maintainer: Troy Straszheim <straszheim@willowgarage.com>
Homepage: http://www.ros.org

Catkin-ProjectName: common_msgs
Catkin-CopyrightType:  willowgarage
Catkin-Depends: catkin, genmsg, std_msgs
Catkin-DebRulesType: cmake
